### ISSUE TITLE
makeHuman models is completely white in Unity

### ISSUE THREAD

**Issue by ericflyfly** [softMonkeys/CMPT-726-Final-Project#1]
The eyes of the models is completely white in Unity.

**Comment by ericflyfly** [comment]
Possible solution 1:
Makehuman community post about the same problem in Blender
http://www.makehumancommunity.org/wiki/FAQ:Eyes_are_rendered_completely_white_(or_black)_in_blender

Add plugin to export mhx2 to blender autmatically handle this issue
https://github.com/makehumancommunity/mhx2-makehuman-exchange

Add addons to import mhx2 in blender manually
https://docs.blender.org/manual/en/latest/editors/preferences/addons.html

Possible solution 2 ():
Makehuman community post about the same problem in Blender
http://www.makehumancommunity.org/forum/viewtopic.php?f=7&t=15494

**Comment by hwec0112** [comment]
I tried many different ways including using various version of Blender to import mhx2 and change the textures directly. They do not work. 2.80 blender does not open in Linux ubuntu 20.04.

The problem fixed by changing the type of eyes to "low-poly" instead of "high-poly" in makehuman software.
